"""initial_schema

Revision ID: f307e9766762
Revises: 
Create Date: 2026-05-16 23:44:26.249585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f307e9766762'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mdns', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('firmware_version', sa.Text(), nullable=True),
    sa.Column('total_leds', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preset_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generated_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('light_id', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['light_id'], ['lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('light_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['light_id'], ['lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('light_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('light_id', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('start_led', sa.Integer(), nullable=False),
    sa.Column('stop_led', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['light_id'], ['lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('preset_data', sa.Text(), nullable=False),
    sa.Column('source_light_id', sa.Integer(), nullable=True),
    sa.Column('source_preset_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['preset_categories.id'], ),
    sa.ForeignKeyConstraint(['source_light_id'], ['lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('light_id', sa.Integer(), nullable=False),
    sa.Column('generated_file_id', sa.Integer(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_file_id'], ['generated_files.id'], ),
    sa.ForeignKeyConstraint(['light_id'], ['lights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exported_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_file_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_file_id'], ['generated_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('light_preset_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('light_id', sa.Integer(), nullable=False),
    sa.Column('master_preset_id', sa.Integer(), nullable=False),
    sa.Column('target_preset_id', sa.Integer(), nullable=False),
    sa.Column('target_quick_label', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['light_id'], ['lights.id'], ),
    sa.ForeignKeyConstraint(['master_preset_id'], ['master_presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('light_preset_assignments')
    op.drop_table('exported_files')
    op.drop_table('deployment_history')
    op.drop_table('master_presets')
    op.drop_table('light_segments')
    op.drop_table('imported_files')
    op.drop_table('generated_files')
    op.drop_table('preset_categories')
    op.drop_table('lights')
    op.drop_table('change_log')
    # ### end Alembic commands ###
